<section>

    <h1>Connection</h1>

    <form action="loginPost" method="post">

        <div>
            <label for="username">Nom d'utilisateur</label>
            <input type="text" id="username" name="username">
        </div>
        <div>
            <label for="password">Mot-de-passe</label>
            <input type="password" id="password" name="password">
        </div>
        <div><input type="submit" value="Ce cennecter" class="button"></div>

    </form>

    <p>Vous n'avez pas de compte ? <a href="register">S'inscrire</a>.</p>

</section>