<section class="width70p block-center">

    <h1><?= lang['login']['loginTitle'] ?></h1>

    <?php if(!empty($data['messages'])) require 'view/partials/displayMessage.phtml' ?>

    <!-- login form -->
    <form class="borderAll shadow paddingAll margeAll" action="<?= lang['name'] ?>/loginPost" method="post">

        <!-- email -->
        <div class="flexTD">
            <label class="width100pM width50p" for="email"><?= lang['login']['email'] ?> :</label>
            <input class="width100pM width50p" type="email" id="email" name="email">
        </div>
        <small class="block width50p block-right error" id="E-email"></small>
        <!-- password -->
        <div class="flexTD margeTop">
            <label class="width100pM width50p" for="password"><?= lang['login']['password'] ?> :</label>
            <input class="width100pM width50p" type="password" id="password" name="password">
        </div>
        <div class="margeTop">
            <input class="button block-center" type="submit" value="<?= lang['multi']['login'] ?>">
        </div>

    </form>

    <!-- register link -->
    <p><?= lang['login']['questionDontHaveAccount'] ?> <a title="<?= lang['login']['registerTitle'] ?>" href="<?= lang['name'] ?>/register"><?= lang['login']['register'] ?></a>.</p>

</section>