<h1>Mon compte</h1>

<?php if(!empty($data['messages'])): ?>
    <div class="borderAll shadow margeAll">
        <ul class="listNone">
            <?php foreach($data['messages'] as $message): ?>
                <li class="<?=key($message)?>"><?= $message[key($message)] ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<section class="shadow borderAll paddingAll width70p block-center">
    <article>
        <h2 class="text-left">Nom d'utilisateur : <?= $data['user']['username'] ?> </h2>
        <form action="my-account/change-username" method="post">
            <div class="flexTD">
                <label for="username" class="width100pM width50p block">Nouveau : </label>
                <input id="username" type="text" class="width100pM width50p" name="username">
            </div>
            <small class="block width50p block-right error" id="E-username"></small>
            <input type="submit" class="button margeTop block-center" value="Changer">
        </form>
    </article>
    <article>
        <h2 class="text-left">Adresse mail : <?= $data['user']['email'] ?> </h2>
        <form action="my-account/change-email" method="post">
            <div class="flexTD">
                <label for="email" class="width100pM width50p block">Nouveau : </label>
                <input id="email" type="text" class="width100pM width50p" name="email">
            </div>
            <small class="block width50p block-right error" id="E-email"></small>
            <input type="submit" class="button margeTop block-center" value="Changer">
        </form>
    </article>
    <article>
        <h2 class="text-left">Mot-de-passe : </h2>
        <form action="my-account/change-password" method="post">
            <div class="flexTD margeBottom">
                <label for="password" class="width100pM width50p block">Nouveau : </label>
                <input id="password" type="password" class="width100pM width50p" name="password">
            </div>
            <small class="block width50p block-right error" id="E-password"></small>
            <div class="flexTD">
                <label for="password-confirm" class="width100pM width50p block">Confirmer : </label>
                <input id="password-confirm" type="password" class="width100pM width50p" name="password-confirm">
            </div>
            <small class="block width50p block-right error" id="E-password-confirm"></small>
            <input type="submit" class="button margeTop block-center" value="Changer">
        </form>
    </article>
</section>