<section>
    <h1><?= lang['login']['accountTitle'] ?></h1>
    <?php if(!empty($data['messages'])): ?>
        <article class="borderAll shadow margeAll">
            <?php require 'view/partials/displayMessage.phtml' ?>
        </article>
    <?php endif; ?>
    <!-- profile picture -->
    <article class="shadow borderAll paddingAll width70p block-center">
        <h2 class="text-left"><?= lang['login']['profilePicture'] ?> :</h2>
        <form action="<?= lang['name'] ?>/my-account/change/profile-picture" method="post" enctype="multipart/form-data">
            <div class="flexTD flex-between">
                <img src="<?= $data['user']['image'] ?>" alt="<?= lang['login']['profilePicture'] ?>" class="profilePicture">
                <input id="profilePicture" type="file" class="width100pM width50p" name="profilePicture">
            </div>
            <input type="submit" class="button margeTop block-center" value="<?= lang['login']['change'] ?>">
        </form>
    </article>
    <!-- username -->
    <article class="shadow borderAll paddingAll width70p block-center">
        <h2 class="text-left"><?= lang['login']['username'] ?> : <?= $data['user']['username'] ?> </h2>
        <form action="<?= lang['name'] ?>/my-account/change/username" method="post">
            <div class="flexTD">
                <label for="username" class="width100pM width50p block"><?= lang['login']['new'] ?> : </label>
                <input id="username" type="text" class="width100pM width50p" name="username">
            </div>
            <small class="block width50p block-right error" id="E-username"></small>
            <input type="submit" class="button margeTop block-center" value="<?= lang['login']['change'] ?>">
        </form>
    </article>
    <!-- email -->
    <article class="shadow borderAll paddingAll width70p block-center">
        <h2 class="text-left"><?= lang['login']['email'] ?> : <?= $data['user']['email'] ?> </h2>
        <form action="<?= lang['name'] ?>/my-account/change/email" method="post">
            <div class="flexTD">
                <label for="email" class="width100pM width50p block"><?= lang['login']['new'] ?> : </label>
                <input id="email" type="text" class="width100pM width50p" name="email">
            </div>
            <small class="block width50p block-right error" id="E-email"></small>
            <input type="submit" class="button margeTop block-center" value="<?= lang['login']['change'] ?>">
        </form>
    </article>
    <!-- password -->
    <article class="shadow borderAll paddingAll width70p block-center">
        <h2 class="text-left"><?= lang['login']['password'] ?> : </h2>
        <form action="<?= lang['name'] ?>/my-account/change/password" method="post">
            <div class="flexTD margeBottom">
                <label for="password" class="width100pM width50p block"><?= lang['login']['new'] ?> : </label>
                <input id="password" type="password" class="width100pM width50p" name="password">
            </div>
            <small class="block width50p block-right error" id="E-password"></small>
            <div class="flexTD">
                <label for="password-confirm" class="width100pM width50p block"><?= lang['login']['confirm'] ?> : </label>
                <input id="password-confirm" type="password" class="width100pM width50p" name="password-confirm">
            </div>
            <small class="block width50p block-right error" id="E-password-confirm"></small>
            <input type="submit" class="button margeTop block-center" value="<?= lang['login']['change'] ?>">
        </form>
    </article>
</section>