<section>

    <h1>Enregistrement</h1>

    <div>
        <ul>
            <?php foreach($data['messages'] as $message): ?>
                <li class="<?=key($message)?>"><?= $message[key($message)] ?></li>
            <?php endforeach; ?>
        </ul>
    </div>

    <form action="registerPost" method="post">

        <div>
            <label for="username">Nom d'utilisateur</label>
            <input type="text" id="username" name="username">
        </div>
        <div>
            <label for="email">Adresse mail</label>
            <input type="email" id="email" name="email">
        </div>
        <div>
            <label for="password">Mot-de-passe</label>
            <input type="password" id="password" name="password">
        </div>
        <div>
            <label for="password-confirm">Confirmation du mot-de-passe</label>
            <input type="password" id="password-confirm" name="password-confirm">
        </div>
        <div><input type="submit" value="S'inscrire" class="button"></div>

    </form>

</section>