<section class="width70p block-center">

    <h1>Inscription</h1>

    <?php if(!empty($data['messages'])): ?>
        <div class="borderAll shadow margeAll">
            <ul class="listNone">
                <?php foreach($data['messages'] as $message): ?>
                    <li class="<?=key($message)?>"><?= $message[key($message)] ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <form class="borderAll shadow paddingAll margeAll" action="/registerPost" method="post">

        <div class="flexTD">
            <label class="width100pM width50p" for="username">Nom d'utilisateur :</label>
            <input class="width100pM width50p" type="text" id="username" name="username">
        </div>
        <small class="block width50p block-right error" id="E-username"></small>
        <div class="flexTD margeTop">
            <label class="width100pM width50p" for="email">Adresse mail :</label>
            <input class="width100pM width50p" type="email" id="email" name="email">
        </div>
        <small class="block width50p block-right error" id="E-email"></small>
        <div class="flexTD margeTop">
            <label class="width100pM width50p" for="password">Mot-de-passe :</label>
            <input class="width100pM width50p" type="password" id="password" name="password">
        </div>
        <small class="block width50p block-right error" id="E-password"></small>
        <div class="flexTD margeTop ">
            <label class="width100pM width50p" for="password-confirm">Confirmation du mot-de-passe :</label>
            <input class="width100pM width50p" type="password" id="password-confirm" name="password-confirm">
        </div>
        <small class="block width50p block-right error" id="E-password-confirm"></small>
        <div class="margeTop">
            <input class="button block-center" type="submit" value="S'inscrire" class="button">
        </div>

    </form>

    <p>Vous avez déjà un compte ? <a href="/login">Se connecter</a>.</p>

</section>