<section class="width70p block-center ">
    <h1>Présentation</h1>
    <article class="borderAll shadow hidden">
        <img src="<?= $data['artwork']->image ?>" alt="<?= $data['artwork']->name ?>" class="width100pM fLeftTD width50p">
        <div class="paddingAll">
            <h2 class="sizeTitle bold text-left noAftBef"><?= $data['artwork']->name ?></h2>
            <p><?= lang['multi']['createdBy'] ?> : <?= $data['artwork']->author ?></p>
            <p><?= lang['multi']['numberVolume'] ?> : <?= $data['artwork']->number_volume ?></p>
            <p><?= lang['multi']['type'] ?> : <?= $data['artwork']->type ?></p>
            <p><?= lang['multi']['genre'] ?> : <?= is_array($data['artwork']->genre)? implode(', ', $data['artwork']->genre) : $data['artwork']->genre ?></p>
        </div>
    </article>
</section>

<?php if($data['isLogin']) : ?>
<section class="width70p block-center">
    <h1><?= lang['artworkInfo']['addComment'] ?></h1>

    <?php if(!empty($data['messages'])): ?>
        <div class="borderAll shadow margeAll">
            <ul class="listNone">
                <?php foreach($data['messages'] as $message): ?>
                    <li class="<?=key($message)?>"><?= $message[key($message)] ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <form   action="<?= lang['name'] ?>/<?= strtolower($data['artwork']->type) ?>/addComment?name=<?= $data['artwork']->slug ?>" 
            method="post"
            class="jsNotRefresh" 
            data-refresh="" 
            data-refresh-with="comment">

        
        <input type="hidden" name="artwork_id" value="<?= $data['artwork']->id ?>">
        <div class="paddingRL">
            <label for="note"><?= lang['multi']['mark'] ?> : </label>
            <input type="number" name="note" id="note" min="0" max="10" class="inputNote paddingAllMin borderAll shadow">
            <span>/10</span>
        </div>
        <div class="paddingRL">
            <textarea name="content" class="paddingAllMin borderAll shadow"></textarea>
        </div>
        <input type="submit" value="<?= lang['multi']['add'] ?>" class="button block-center">
    </form>
</section>
<?php endif; ?>

<?php if(!empty($data['comments'])): ?>
    <section>
        <h1><?= lang['artworkInfo']['comment'] ?></h1>
        <div>
            <?php foreach($data['comments'] as $comment): ?>
                <article class="width70p block-center paddingAll borderAll shadow">
                    <h3 class="text-left"><span><?= $comment->note ?>/10</span></h3>
                    <div class="flex flex-align-center"><img src="<?= $comment->userPicture ?>" class="profilePicture" alt="logo"> <span class="margeLR bold"><?= $comment->user ?></span></div>
                    <p><?= nl2br($comment->content) ?></p>
                </article>
            <?php endforeach; ?>
        </div>
    </section>
<?php endif; ?>










