<!-- nav (Anime, Mange, All) -->
<nav class="flex-around width50p block-center">
    <a title="Anime" href="<?= lang['name'] ?>/my-list/anime" class="navButton">Anime</a>
    <a title="Manga" href="<?= lang['name'] ?>/my-list/manga" class="navButton">Manga</a>
    <a title="<?= lang['multi']['all'] ?>" href="<?= lang['name'] ?>/my-list/all" class="navButton"><?= lang['multi']['all'] ?></a>
</nav>

<!-- List artwork -->
<section class="grid-3 paddingRL">

    <input id="JStype" type="hidden" name="type" value="<?=strtolower($data['type'])?>">
    <h1 class="grid-fullWidth"><?= lang['myList']['title'][$data['type']] ?></h1>

    <div class="grid-fullWidth shadow borderAll paddingAll widthMaxContent block-center">
        <label for="search"><?= lang['multi']['search'] ?> : </label>
        <input class="width30rem" type="search" id="search" disabled>
    </div>

    <?php foreach($data['list'] as $artwork): ?>
        <article class="shadow borderAll">
            <?php require 'view/partials/displayArtwork.phtml' ?>
        </article>
    <?php endforeach; ?>

</section>