<section>
    <nav class="flex-around width50p block-center">
        <a href="/my-list/anime" class="navButton">Anime</a>
        <a href="/my-list/manga" class="navButton">Manga</a>
        <a href="/my-list/all" class="navButton">Tous</a>
    </nav>
</section>

<section class="grid-3 paddingRL">

    <input id="JStype" type="hidden" name="type" value="<?=strtolower($data['type'])?>">
    <h1 class="grid-fullWidth">Ma liste <?= $data['titleType'] ?></h1>

    <div class="grid-fullWidth shadow borderAll paddingAll widthMaxContent block-center">
        <label for="search">Recherche : </label>
        <input class="width30rem" type="search" name="" id="search" disabled>
    </div>

    <?php foreach($data['list'] as $artwork): ?>
        <article class="shadow borderAll">
            <figure class="hover-caption" tabindex="0">
                <img src="<?= $artwork->image ?>" alt="<?= $artwork->name ?>">
                <form class="user-status" action="/set-artwork-list-status" method="post">
                    <input type="hidden" name="artwork_id" value="<?= $artwork->id ?>">
                    <select  name="status" id="changeStatusSelect">
                        <?php foreach($data['status'] as $status ): ?>
                            <option value="<?= $status->id ?>" <?= $artwork->status_id === $status->id ? 'selected' : '' ?>><?= $status->name ?></option>
                        <?php endforeach; ?>
                    </select>
                    <button type="submit" id="changeStatusButton">Changer</button>
                </form>
                <figcaption>
                    <div>
                        <h3><?= $artwork->name ?></h3>
                        <p>Créer par : <?= $artwork->author ?></p>
                        <?php if (!empty($artwork->genre)): ?>
                            <p>Genre : <?= is_array($artwork->genre)? implode(', ', $artwork->genre) : $artwork->genre ?></p>
                        <?php endif; ?>
                        <?php if (!empty($artwork->note)): ?>
                            <p>Note : <?= $artwork->note ?>/10</p>
                        <?php endif; ?>
                        <a href="/<?= strtolower($artwork->type) ?>/info?name=<?= $artwork->slug ?>" class="button block-center">Plus d'info</a>
                    </div>
                    <form action="/remove-artwork-list" method="post">
                        <input type="hidden" name="artwork_id" value="<?= $artwork->id ?>">
                        <button id="removeArtworkList" class="artwork-list-button remove"></button>
                    </form>
                </figcaption>
                
            </figure>
        </article>
    <?php endforeach; ?>

</section>