<section id="refresh" class="grid-3 paddingRL">

    <input id="JStype" type="hidden" name="type" value="<?=strtolower($data['type'])?>">
    <h1 class="grid-fullWidth"><?= lang['search']['listOf'] ?> <?= $data['type'] ?>s</h1>

    <div class="grid-fullWidth shadow borderAll paddingAll widthMaxContent block-center">
        <label for="search"><?= lang['multi']['search'] ?> : </label>
        <input class="width30rem" type="search" name="" id="search" disabled>
    </div>

    <?php foreach($data['list'] as $artwork): ?>
        <article class="shadow borderAll">
            <?php require 'view/partials/displayArtwork.phtml' ?>
        </article>
    <?php endforeach; ?>

</section>