

<section class="grid-3 paddingRL">

    <h1>Liste des <?= $data['type'] ?>s</h1>

    <?php foreach($data['list'] as $artwork): ?>
        <article class="shadow borderAll">
            <figure class="hover-caption" tabindex="0">
                <img src="<?= $artwork->image ?>" alt="<?= $artwork->name ?>">
                <?php if($data['isLogin'] && !empty($data['user_list'][$artwork->id])): ?>
                    <span class="user-status"><?= $data['user_list'][$artwork->id] ?></span>
                <?php endif; ?>
                <figcaption>
                    <div>
                        <h3><?= $artwork->name ?></h3>
                        <p>Créer par : <?= $artwork->author ?></p>
                        <?php if (!empty($artwork->genre)): ?>
                            <p>Genre : <?= is_array($artwork->genre)? implode(', ', $artwork->genre) : $artwork->genre ?></p>
                        <?php endif; ?>
                        <?php if (!empty($artwork->note)): ?>
                            <p>Note : <?= $artwork->note ?>/10</p>
                        <?php endif; ?>
                        <a href="/<?= strtolower($data['type']) ?>/info?name=<?= $artwork->slug ?>" class="button block-center">Plus d'info</a>
                    </div>
                    <?php if($data['isLogin']): ?>
                        <form action="<?= empty($data['user_list'][$artwork->id]) ? '/add-artwork-list' : '/remove-artwork-list'?>" method="post">
                            <input type="hidden" name="artwork_id" value="<?= $artwork->id ?>">
                            <?php if(empty($data['user_list'][$artwork->id])): ?>
                                <button class="add-artwork-button">+</button>
                            <?php else: ?>
                                <button class="add-artwork-button"><span>_</span></button>
                            <?php endif; ?>
                        </form>
                    <?php endif; ?>
                </figcaption>
                
            </figure>
        </article>
    <?php endforeach; ?>

</section>