<div>
    <ul>
        <?php foreach($data['messages'] as $message): ?>
            <li class="<?=key($message)?>"><?= $message[key($message)] ?></li>
        <?php endforeach; ?>
    </ul>
</div>
                        <!-- Anime -->
<section>
                            <!-- list -->
    <article>
        <input type="checkbox" id="list-anime" class="admin-check">
        <label for="list-anime">Liste des animes</label>
        <div>
            <table class="border">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>nom</th>
                        <th>studio</th>
                        <th>nombre d'épisodes</th>
                        <th>genre(s)</th>
                        <th>image</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data['animes'] as $anime): ?>
                    <tr>
                        <td><?= $anime->id ?></td>
                        <td><?= $anime->name ?></td>
                        <td><?= $anime->author?></td>
                        <td><?= $anime->number_volume?></td>
                        <td><?= is_array($anime->genre)? implode(', ', $anime->genre) : $anime->genre ?></td>
                        <td><?= $anime->image ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </article>
                            <!-- add -->
    <article>
        <input type="checkbox" id="add-anime" class="admin-check">
        <label for="add-anime">Ajouter un anime</label>
        <div>

            <form action="/admin/add/artwork" method="post" enctype="multipart/form-data">
                <input type="hidden" name="type" value="2">
                <div>
                    <label for="anime-name">Nom</label>
                    <input type="text" id="anime-name" name="name">
                </div>
                <div>
                    <label for="anime-author">Auteur</label>
                    <select id="anime-author" name="author">
                        <?php foreach($data['authors'] as $author): ?>
                            <option value="<?= $author->id ?>"><?= $author->name ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div>
                    <label for="anime-number-volume">Nombre d'épisode</label>
                    <input type="number" id="anime-number-volume" name="number_volume" min="0">
                </div>
                <div>
                    <span>Genres : </span>
                    <?php foreach($data['genres'] as $genre): ?>
                        <input type="checkbox" id="anime-genre-<?= $genre->id ?>" name="genres[]" value="<?= $genre->id ?>">
                        <label for="anime-genre-<?= $genre->id ?>"><?= $genre->name ?></label>
                    <?php endforeach; ?>
                </div>
                <div>
                    <label for="anime-image">Image</label>
                    <input type="file" id="anime-image" name="image">
                </div>
                <input type="submit" value="Ajouter">
            </form>

        </div>
    </article>
</section>

                            <!-- manga -->
<section>
                            <!-- list -->
    <article>
        <input type="checkbox" id="list-manga" class="admin-check">
        <label for="list-manga">Liste des mangas</label>
        <div>
            <table class="border">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>nom</th>
                        <th>auteur</th>
                        <th>nombre de volumes</th>
                        <th>genre(s)</th>
                        <th>image</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data['mangas'] as $manga): ?>
                    <tr>
                        <td><?= $manga->id ?></td>
                        <td><?= $manga->name ?></td>
                        <td><?= $manga->author?></td>
                        <td><?= $manga->number_volume?></td>
                        <td><?= is_array($manga->genre)? implode(', ', $manga->genre) : $manga->genre ?></td>
                        <td><?= $manga->image ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </article>
                                <!-- add -->
    <article>
        <input type="checkbox" id="add-manga" class="admin-check">
        <label for="add-manga">Ajouter un manga</label>
        <div>
            <form action="/admin/add/artwork" method="post" enctype="multipart/form-data">
                <input type="hidden" name="type" value="1">
                <div>
                    <label for="manga-name">Nom</label>
                    <input type="text" id="manga-name" name="name">
                </div>
                <div>
                    <label for="manga-author">Auteur</label>
                    <select id="manga-author" name="author">
                        <?php foreach($data['authors'] as $author): ?>
                            <option value="<?= $author->id ?>"><?= $author->name ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div>
                    <label for="manga-number-volume">Nombre d'épisode</label>
                    <input type="number" id="manga-number-volume" name="number_volume" min="0">
                </div>
                <div>
                    <span>Genres : </span>
                    <?php foreach($data['genres'] as $genre): ?>
                        <input type="checkbox" id="manga-genre-<?= $genre->id ?>" name="genres[]" value="<?= $genre->id ?>">
                        <label for="manga-genre-<?= $genre->id ?>"><?= $genre->name ?></label>
                    <?php endforeach; ?>
                </div>
                <div>
                    <label for="manga-image">Image</label>
                    <input type="file" id="manga-image" name="image">
                </div>
                <input type="submit" value="Ajouter">
            </form>
        </div>
    </article>

</section>