<div>
    <ul>
        <?php foreach($data['messages'] as $message): ?>
            <li class="<?=key($message)?>"><?= $message[key($message)] ?></li>
        <?php endforeach; ?>
    </ul>
</div>
                        <!-- Artwork -->
<section>
    <h1>Artwork</h1>
                            <!-- lists -->
    <article>
                                <!-- Anime -->
        <input type="checkbox" id="list-anime" class="admin-check">
        <label for="list-anime">Liste des animes</label>
        <div>
            <table class="border">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>nom</th>
                        <th>studio</th>
                        <th>nombre d'épisodes</th>
                        <th>genre(s)</th>
                        <th>image</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data['animes'] as $anime): ?>
                    <tr>
                        <td><?= $anime->id ?></td>
                        <td><?= $anime->name ?></td>
                        <td><?= $anime->author?></td>
                        <td><?= $anime->number_volume?></td>
                        <td><?= is_array($anime->genre)? implode(', ', $anime->genre) : $anime->genre ?></td>
                        <td><?= $anime->image ?></td>
                        <td><a href="<?= lang['name'] ?>/admin/artwork/edit/<?= $anime->id ?>">Editer</a></td>
                        <td><a href="<?= lang['name'] ?>/admin/artwork/remove/<?= $anime->id ?>">X</a></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </article>

    <article>
                                <!-- Manga -->
        <input type="checkbox" id="list-manga" class="admin-check">
        <label for="list-manga">Liste des mangas</label>
        <div>
            <table class="border">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>nom</th>
                        <th>auteur</th>
                        <th>nombre de volumes</th>
                        <th>genre(s)</th>
                        <th>image</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data['mangas'] as $manga): ?>
                    <tr>
                        <td><?= $manga->id ?></td>
                        <td><?= $manga->name ?></td>
                        <td><?= $manga->author?></td>
                        <td><?= $manga->number_volume?></td>
                        <td><?= is_array($manga->genre)? implode(', ', $manga->genre) : $manga->genre ?></td>
                        <td><?= $manga->image ?></td>
                        <td><a href="<?= lang['name'] ?>/admin/artwork/edit/<?= $manga->id ?>">Editer</a></td>
                        <td><a href="<?= lang['name'] ?>/admin/artwork/remove/<?= $manga->id ?>">X</a></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </article>
                            <!-- add Artwork -->
    <article>
        <input type="checkbox" id="add-artwork" class="admin-check">
        <label for="add-artwork">Ajouter un artwork</label>
        <div>

            <form action="<?= lang['name'] ?>/admin/add/artwork" method="post" enctype="multipart/form-data">
                <div>
                    <label for="type">Type</label>
                    <select name="type" id="type">
                        <option value="Manga">Manga</option>
                        <option value="Anime">Anime</option>
                    </select>
                </div>
                <div>
                    <label for="artwork-name">Nom</label>
                    <input type="text" id="artwork-name" name="name">
                </div>
                <div>
                    <label for="artwork-author">Auteur</label>
                    <select id="artwork-author" name="author">
                        <?php foreach($data['authors'] as $author): ?>
                            <option value="<?= $author->id ?>"><?= $author->name ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div>
                    <label for="artwork-number-volume">Nombre d'épisode</label>
                    <input type="number" id="artwork-number-volume" name="number_volume" min="0">
                </div>
                <div>
                    <span>Genres : </span>
                    <?php foreach($data['genres'] as $genre): ?>
                        <input type="checkbox" id="artwork-genre-<?= $genre->id ?>" name="genres[]" value="<?= $genre->id ?>">
                        <label for="artwork-genre-<?= $genre->id ?>"><?= $genre->name ?></label>
                    <?php endforeach; ?>
                </div>
                <div>
                    <label for="artwork-image">Image</label>
                    <input type="file" id="artwork-image" name="image">
                </div>
                <div>
                    <label for="release_date ">Date</label>
                    <input type="date" name="release_date">
                </div>
                <input type="submit" value="Ajouter">
            </form>

        </div>
    </article>
</section>

<section>

<section>
                        <!-- Authors/Studio -->
    <h1>Auteurs/Studios</h1>
    <article>
                            <!-- List -->
        <input type="checkbox" id="list-author" class="admin-check">
        <label for="list-author">Liste des Auteurs/Studios</label>
        <div>
            <table class="border">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>nom</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data['authors'] as $author): ?>
                    <tr>
                        <td><?= $author->id ?></td>
                        <td><?= $author->name ?></td>
                        <td><a href="<?= lang['name'] ?>/admin/author/edit/<?= $author->id ?>">Editer</a></td>
                        <td><a href="<?= lang['name'] ?>/admin/author/remove/<?= $author->id ?>">X</a></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </article>

    <article>
        <input type="checkbox" id="add-author" class="admin-check">
        <label for="add-author">Ajouter un Auteur/Studio</label>
        <div>
            <form action="<?= lang['name'] ?>/admin/add/author" method="post">
                <div>
                    <label for="name">Nom</label>
                    <input id="name" type="text" name="name">
                </div>
                <input type="submit">
            </form>
        </div>
    </article>

</section>

                        <!-- Genres -->
<h1>Genres</h1>
    <article>
                            <!-- List -->
        <input type="checkbox" id="list-genre" class="admin-check">
        <label for="list-genre">Liste des Genres</label>
        <div>
            <table class="border">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>nom</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data['genres'] as $genre): ?>
                    <tr>
                        <td><?= $genre->id ?></td>
                        <td><?= $genre->name ?></td>
                        <td><a href="<?= lang['name'] ?>/admin/genre/edit/<?= $genre->id ?>">Editer</a></td>
                        <td><a href="<?= lang['name'] ?>/admin/genre/remove/<?= $genre->id ?>">X</a></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </article>

    <article>
        <input type="checkbox" id="add-genre" class="admin-check">
        <label for="add-genre">Ajouter un Genre</label>
        <div>
            <form action="<?= lang['name'] ?>/admin/add/genre" method="post">
                <div>
                    <label for="name">Nom</label>
                    <input id="name" type="text" name="name">
                </div>
                <input type="submit">
            </form>
        </div>
    </article>

</section>