<?php use App\Core\Session; ?>
<!DOCTYPE html>
<html lang="<?= lang['name'] ?>">
<head>
    <meta charset="UTF-8">
    <base href="<?= config['baseUrl'] ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="ressources/img/logo.png" />
    <!-- importations -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"> <!-- Importation de normalize.css -->
    <!-- mon css -->
    <link rel="stylesheet" href="ressources/css/style.css">
    <title>Weebsithèque | <?= $title ?></title>
</head>
<body>
    <header>
        <div class="container">
            <a href="<?= lang['name'] ?>/" class="logo"><h1>Weebsithèque</h1></a>
            <div class="connect navigation">
                <?php if(Session::isLogin()): ?>
                    <ul>
                        <li>
                            <input type="checkbox" id="nav-user" class="nav-check">
                            <label for="nav-user"><?= Session::getUser()['username'] ?></label>
                            <ul>
                                <li><a href="<?= lang['name'] ?>/my-account"><?= lang['nav-login']['myAccount'] ?></a></li>
                                <li><a href="<?= lang['name'] ?>/my-list/all"><?= lang['nav-login']['userLists'] ?></a></li>
                                <?php if(Session::getUser()['isAdmin']): ?>
                                    <li><a href="<?= lang['name'] ?>/admin"><?= lang['nav-login']['adminPage'] ?></a></li>
                                <?php endif; ?>
                                <li ><a href="<?= lang['name'] ?>/logout"><?= lang['nav-login']['logout'] ?></a></li>
                            </ul>
                        </li>
                    </ul>
                <?php else: ?>
                    <a href="<?= lang['name'] ?>/login"><?= Session::isLogin()? Session::getUser()['username'] : lang['multi']['login'] ?></a>
                <?php endif; ?>
            </div>
            <nav class="navigation">
                <ul>
                    <li><a href="<?= lang['name'] ?>/"><?= lang['nav']['home'] ?></a></li>
                    <li>
                        <input type="checkbox" id="nav-anime" class="nav-check">
                        <label for="nav-anime">Anime</label>
                        <ul>
                            <?php if(Session::isLogin()): ?>
                                <li><a href="<?= lang['name'] ?>/my-list/anime"><?= lang['nav']['myList'] ?></a></li> <!-- si connecter -->
                            <?php endif; ?>
                            <li><a href="<?= lang['name'] ?>/anime/search"><?= lang['multi']['search'] ?></a></li>
                        </ul>
                    </li>
                    <li>
                        <input type="checkbox" id="nav-manga" class="nav-check">
                        <label for="nav-manga">Manga</label>
                        <ul>
                            <?php if(Session::isLogin()): ?>
                                <li><a href="<?= lang['name'] ?>/my-list/manga"><?= lang['nav']['myList'] ?></a></li> <!-- si connecter -->
                            <?php endif; ?>
                            <li><a href="<?= lang['name'] ?>/manga/search"><?= lang['multi']['search'] ?></a></li>
                        </ul>
                    </li>
                    <li>
                        <input type="checkbox" id="nav-diver" class="nav-check">
                        <label for="nav-diver"><?= lang['nav']['various'] ?></label>
                        <ul>
                            <li><a href="<?= lang['name'] ?>/diver/waifu">Waifus</a></li> 
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <main>
        <div class="container">
            <?php require $view ?>
        </div>
    </main>
    <footer>
        <div class="container">
            <p class="sign">Zirnheld Cédric</p>
        </div>
    </footer>

    <script src="ressources/js/main.js" type="module"></script>
</body>
</html>