<?php

use App\Core\Session;
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="/ressources/img/logo.png" />
    <!-- importations -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"> <!-- Importation de normalize.css -->
    <!-- mon css -->
    <link rel="stylesheet" href="/ressources/css/style.css">
    <title>Weebsithèque | <?= $title ?></title>
</head>
<body>
    <header>
        <div class="container">
            <a href="/" class="logo"><h1>Weebsithèque</h1></a>
            <div class="connect <?= Session::isLogin() ? 'navigation' : ''?> ">
                <?php if(Session::isLogin()): ?>
                    <ul>
                        <li>
                            <input type="checkbox" id="nav-user" class="nav-check">
                            <label for="nav-user"><?= Session::getUser()['username'] ?></label>
                            <ul>
                                <li><a href="#">Mon compte</a></li>
                                <li><a href="#">Mes listes</a></li>
                                <?php if(Session::getUser()['isAdmin']): ?>
                                    <li><a href="/admin">Page administrateur</a></li>
                                <?php endif; ?>
                                <li ><a href="/logout">Se déconnecter</a></li>
                            </ul>
                        </li>
                    </ul>
                <?php else: ?>
                    <a href="/login"><?= Session::isLogin()? Session::getUser()['username'] : 'Ceux kaunnaiqueté' ?></a>
                <?php endif; ?>
            </div>
            <nav class="navigation">
                <ul>
                    <li><a href="/">Acceuil</a></li>
                    <li>
                        <input type="checkbox" id="nav-anime" class="nav-check">
                        <label for="nav-anime">Anime</label>
                        <ul>
                            <?php if(Session::isLogin()): ?>
                                <li><a href="/my-anime-list">Ma liste</a></li> <!-- si connecter -->
                            <?php endif; ?>
                            <li><a href="/anime/search">Recherche</a></li>
                        </ul>
                    </li>
                    <li>
                        <input type="checkbox" id="nav-manga" class="nav-check">
                        <label for="nav-manga">Manga</label>
                        <ul>
                            <?php if(Session::isLogin()): ?>
                                <li><a href="/my-manga-list">Ma liste</a></li> <!-- si connecter -->
                            <?php endif; ?>
                            <li><a href="/manga/search">Recherche</a></li>
                        </ul>
                    </li>
                    <li>
                        <input type="checkbox" id="nav-diver" class="nav-check">
                        <label for="nav-diver">Divers</label>
                        <ul>
                            <li><a href="/waifu">Waifus</a></li> 
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <main>
        <div class="container">
            <?php require $view ?>
        </div>
    </main>
    <footer>
        <div class="container">
            <p class="sign">Zirnheld Cédric</p>
        </div>
    </footer>

    <script src="/ressources/js/main.js"></script>
</body>
</html>