<section>
    <h1><?= lang['home']['welcome']['title'] ?></h1>
    <p class="width70p block-center"><?= lang['home']['welcome']['text1'] ?></p>
</section>


<section class="flex flexWrap flex-around">
    <h1 class="width100p"><?= lang['home']['bestMark']['title'] ?></h1>
    <article class="width50p paddingRL">

        <h2>Anime</h2>
        <div class="carousel block-center">

            <?php foreach( $data['bestMark']['anime'] as $artwork ): ?>
                <div><?php require 'view/partials/displayArtwork.phtml'; ?></div>
            <?php endforeach; ?>

            
        </div>

    </article>
    <article class="width50p paddingRL">

        <h2>Mangas</h2>
        <div class="carousel block-center">

            <?php foreach( $data['bestMark']['manga'] as $artwork ): ?>
                <div><?php require 'view/partials/displayArtwork.phtml'; ?></div>
            <?php endforeach; ?>

        </div>
    </article>

</section>

<section class="flex flexWrap flex-around">
    <h1 class="width100p"><?= lang['home']['new']['title'] ?></h1>
    <article class="width50p paddingRL">
        <h2>Anime</h2>
        <div class="carousel block-center">

            <?php foreach( $data['new']['anime'] as $artwork ): ?>
                <div><?php require 'view/partials/displayArtwork.phtml'; ?></div>
            <?php endforeach; ?>

        </div>
    </article>
    <article class="width50p paddingRL">
        <h2>Mangas</h2>
        <div class="carousel block-center">

            <?php foreach( $data['new']['manga'] as $artwork ): ?>
                <div><?php require 'view/partials/displayArtwork.phtml'; ?></div>
            <?php endforeach; ?>
            
        </div>
    </article>
</section>